---
title: Steam Dream
author: Paul Clarke
email: noahwclarke@gmail.com
description: Steam Dream is a handmade steampunk-inspired pinball machine. With numerous
  unique elements and gameplay features, Steam Dream exists on the cutting edge of
  pinball design.
baseurl: "/"
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
